-- ============================================
-- MUSIC STREAMING PLATFORM
-- TABLE CREATION SCRIPT
-- Oracle Database Free
-- ============================================

CREATE TABLE app_user (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(50) NOT NULL,
    middle_name VARCHAR2(50),
    last_name VARCHAR2(50),
    email VARCHAR2(150) NOT NULL,
    phone_no VARCHAR2(20),
    gender VARCHAR2(20),
    dob DATE,

    CONSTRAINT pk_app_user PRIMARY KEY (user_id),
    CONSTRAINT uq_app_user_email UNIQUE (email)
);


CREATE TABLE artist (
    artist_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(150) NOT NULL,
    bio CLOB,
    social_media VARCHAR2(500),

    CONSTRAINT pk_artist PRIMARY KEY (artist_id)
);


CREATE TABLE podcast_creator (
    creator_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR2(150) NOT NULL,
    bio CLOB,

    CONSTRAINT pk_podcast_creator PRIMARY KEY (creator_id),
    CONSTRAINT uq_creator_email UNIQUE (email)
);


CREATE TABLE playlist (
    playlist_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER NOT NULL,
    playlist_name VARCHAR2(150) NOT NULL,
    created_date DATE DEFAULT SYSDATE,
    visibility VARCHAR2(20) DEFAULT 'PRIVATE',

    CONSTRAINT pk_playlist PRIMARY KEY (playlist_id),
    CONSTRAINT fk_playlist_user
        FOREIGN KEY (user_id)
        REFERENCES app_user(user_id),

    CONSTRAINT chk_playlist_visibility
        CHECK (visibility IN ('PUBLIC', 'PRIVATE'))
);


CREATE TABLE subscription (
    subscription_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER NOT NULL,
    plan_type VARCHAR2(50) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,

    CONSTRAINT pk_subscription PRIMARY KEY (subscription_id),

    CONSTRAINT fk_subscription_user
        FOREIGN KEY (user_id)
        REFERENCES app_user(user_id)
);

CREATE TABLE device (
    device_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER NOT NULL,
    os VARCHAR2(50),
    device_type VARCHAR2(50),

    CONSTRAINT pk_device PRIMARY KEY (device_id),

    CONSTRAINT fk_device_user
        FOREIGN KEY (user_id)
        REFERENCES app_user(user_id)
);


CREATE TABLE album (
    album_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    artist_id NUMBER NOT NULL,
    album_title VARCHAR2(200) NOT NULL,
    release_date DATE,
    cover_page VARCHAR2(500),

    CONSTRAINT pk_album PRIMARY KEY (album_id),

    CONSTRAINT fk_album_artist
        FOREIGN KEY (artist_id)
        REFERENCES artist(artist_id)
);


CREATE TABLE song (
    song_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    album_id NUMBER,
    artist_id NUMBER NOT NULL,
    name VARCHAR2(200) NOT NULL,
    duration NUMBER,
    release_date DATE,
    audio_url VARCHAR2(500),

    CONSTRAINT pk_song PRIMARY KEY (song_id),

    CONSTRAINT fk_song_album
        FOREIGN KEY (album_id)
        REFERENCES album(album_id),

    CONSTRAINT fk_song_artist
        FOREIGN KEY (artist_id)
        REFERENCES artist(artist_id)
);


CREATE TABLE playlist_song (
    playlist_id NUMBER NOT NULL,
    song_id NUMBER NOT NULL,
    added_date DATE DEFAULT SYSDATE,

    CONSTRAINT pk_playlist_song
        PRIMARY KEY (playlist_id, song_id),

    CONSTRAINT fk_ps_playlist
        FOREIGN KEY (playlist_id)
        REFERENCES playlist(playlist_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_ps_song
        FOREIGN KEY (song_id)
        REFERENCES song(song_id)
        ON DELETE CASCADE
);


CREATE TABLE user_artist (
    user_id NUMBER NOT NULL,
    artist_id NUMBER NOT NULL,
    followed_date DATE DEFAULT SYSDATE,

    CONSTRAINT pk_user_artist
        PRIMARY KEY (user_id, artist_id),

    CONSTRAINT fk_ua_user
        FOREIGN KEY (user_id)
        REFERENCES app_user(user_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_ua_artist
        FOREIGN KEY (artist_id)
        REFERENCES artist(artist_id)
        ON DELETE CASCADE
);


CREATE TABLE podcast (
    podcast_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    creator_id NUMBER NOT NULL,
    title VARCHAR2(200) NOT NULL,
    language VARCHAR2(50),
    release_date DATE,
    description CLOB,

    CONSTRAINT pk_podcast PRIMARY KEY (podcast_id),

    CONSTRAINT fk_podcast_creator
        FOREIGN KEY (creator_id)
        REFERENCES podcast_creator(creator_id)
);


CREATE TABLE episode (
    episode_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    podcast_id NUMBER NOT NULL,
    episode_no NUMBER NOT NULL,
    title VARCHAR2(200) NOT NULL,
    duration NUMBER,
    description CLOB,
    release_date DATE,
    audio_url VARCHAR2(500),

    CONSTRAINT pk_episode PRIMARY KEY (episode_id),

    CONSTRAINT fk_episode_podcast
        FOREIGN KEY (podcast_id)
        REFERENCES podcast(podcast_id)
        ON DELETE CASCADE,

    CONSTRAINT uq_episode_number
        UNIQUE (podcast_id, episode_no)
);

CREATE TABLE payment (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER NOT NULL,
    subscription_id NUMBER,
    amount NUMBER(10,2) NOT NULL,
    payment_mode VARCHAR2(30),
    payment_date DATE DEFAULT SYSDATE,

    CONSTRAINT pk_payment PRIMARY KEY (payment_id),

    CONSTRAINT fk_payment_user
        FOREIGN KEY (user_id)
        REFERENCES app_user(user_id),

    CONSTRAINT fk_payment_subscription
        FOREIGN KEY (subscription_id)
        REFERENCES subscription(subscription_id),

    CONSTRAINT chk_payment_amount
        CHECK (amount >= 0)
);

-- ============================================
-- TABLE CREATION COMPLETE
-- ============================================

ALTER TABLE app_user ADD password VARCHAR2(255);